//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.22 at 10:21:58 PM CEST 
//


package nl.hanze.moron;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.hanze.moron package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MAP_QNAME = new QName("", "MAP");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.hanze.moron
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MAPType }
     * 
     */
    public MAPType createMAPType() {
        return new MAPType();
    }

    /**
     * Create an instance of {@link OBSTACLEType }
     * 
     */
    public OBSTACLEType createOBSTACLEType() {
        return new OBSTACLEType();
    }

    /**
     * Create an instance of {@link POINTType }
     * 
     */
    public POINTType createPOINTType() {
        return new POINTType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MAPType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MAP")
    public JAXBElement<MAPType> createMAP(MAPType value) {
        return new JAXBElement<MAPType>(_MAP_QNAME, MAPType.class, null, value);
    }

}
